In [30]:
import redcap
import json
import requests
import pandas as pd

# Project Setup

In [31]:
api_key = json.load(open('../PyCap/json_api_data.json'))
api_token = api_key['dev_token']['262']
api_url = api_key['dev_url']

In [32]:
project = redcap.Project(api_url, api_token)

# Gathered Survey Data

## Records

In [62]:
data = {
    'token': api_token,
    'content': 'record',
    'action': 'export',
    'format': 'json',
    'type': 'flat',
    'csvDelimiter': '',
    'records[0]': '2', #chooses which records to export (default if unspecified is all records)
    'rawOrLabel': 'label', #will display the number if 'raw', and the actual option selected if 'label' (for radio buttons/dropdowns) 
    'rawOrLabelHeaders': 'raw', #col names - raw is the variable name and label is the field's question
    'exportCheckboxLabel': 'true', #will just display "checked/unchecked" if false, and will display the actual option checked if true 
    'exportSurveyFields': 'false', #only relevant when surveys are enabled - exports additional fields like timestamps 
    'exportDataAccessGroups': 'false', #only relevant when DAGs are used in the project 
    'returnFormat': 'json'
}
r = requests.post('https://dev-redcap.doh.wa.gov/api/',data=data)
df_json = r.json()
df = pd.DataFrame.from_records(df_json)
df

,record_id,redcap_event_name,redcap_repeat_instrument,redcap_repeat_instance,first_name,last_name,phone_num,zip_code,dob,age,...,cc_phone,cc_email,close_contacts_complete,supervisor_name,supervisor_email,work_inperson_yesno,work_date,work_contagious,work_contagious_calc,work_information_complete
0,2,Personal Info,,,Jane,Doe,(999) 999-9999,98105,1995-06-29,28,...,,,,,,,,,,
1,2,Notifications,,,,,,,,,...,,,,Boss,fake_email@gmail.com,Yes,2023-10-10,Yes,,Complete
2,2,Case Intake,,1,,,,,,,...,,,,,,,,,,
3,2,Case Intake,,2,,,,,,,...,,,,,,,,,,
4,2,Notifications,Close Contacts,1,,,,,,,...,(999) 999-9999,fake_email@gmail.com,Complete,,,,,,,
5,2,Notifications,Close Contacts,2,,,,,,,...,(999) 999-9999,,Incomplete,,,,,,,

In [85]:
data = {
    'token': api_token,
    'content': 'record',
    'action': 'export',
    'format': 'csv',
    'type': 'flat',
    'csvDelimiter': '',
    'records[0]': '2', #chooses which records to export (default if unspecified is all records)
    'rawOrLabel': 'label', #will display the number if 'raw', and the actual option selected if 'label' (for radio buttons/dropdowns) 
    'rawOrLabelHeaders': 'label', #col names - raw is the variable name and label is the field's question
    'exportCheckboxLabel': 'true', #will just display "checked/unchecked" if false, and will display the actual option checked if true 
    'exportSurveyFields': 'false', #only relevant when surveys are enabled - exports additional fields like timestamps 
    'exportDataAccessGroups': 'false', #only relevant when DAGs are used in the project 
    'returnFormat': 'csv'
}
r = requests.post('https://dev-redcap.doh.wa.gov/api/',data=data)
r.text

'"Study ID","Event Name","Repeat Instrument","Repeat Instance","First Name","Last Name","Phone Number","ZIP Code","Date of birth","Age (years)",Ethnicity,Race,Gender,Complete?,"Have you experienced any new symptoms of COVID-19?","When did your symptoms start? ","Which of the following symptoms have you experienced?  (choice=Sore Throat)","Which of the following symptoms have you experienced?  (choice=Cough)","Which of the following symptoms have you experienced?  (choice=Shortness of Breath)","Which of the following symptoms have you experienced?  (choice=Chest Pain)","Which of the following symptoms have you experienced?  (choice=Headache)","Which of the following symptoms have you experienced?  (choice=Runny Nose)","Which of the following symptoms have you experienced?  (choice=Congestion)","Which of the following symptoms have you experienced?  (choice=Fever)","Which of the following symptoms have you experienced?  (choice=Body Aches)","Which of the following symptoms have you experienced?  (choice=Nausea/Vomiting)","Which of the following symptoms have you experienced?  (choice=Diarrhea)","Is there any other symptom you\'d like to report or anything you would like us to know about your symptoms?",Complete?,"Have you recently taken a test for COVID-19?","Did you test positive for COVID-19?","When did you test positive for COVID-19? Use the first positive test date if you tested more than once. ","Upload your test results here (optional):","Have you had COVID-19 before?","When did you test positive for COVID-19 when you had it previously? (Ok to estimate.)",Complete?,"Name of close contact","What day were you last in contact with this person?","Phone number of close contact","Email of close contact",Complete?,"Supervisor Name","Supervisor email","Do you ever work in-person?","Date you last worked in-person?","Was this person at work while contagious? Symptom Onset Date: [case_intake_arm_1][symptom_onset]","Was this person at work while contagious? ",Complete?\n2,"Personal Info",,,Jane,Doe,"(999) 999-9999",98105,1995-06-29,28,"Hispanic or Latino","More Than One Race",Female,Complete,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,\n2,Notifications,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Boss,fake_email@gmail.com,Yes,2023-10-10,Yes,,Complete\n2,"Case Intake",,1,,,,,,,,,,Incomplete,Yes,2023-10-11,"Sore Throat",Cough,,,,,,Fever,,,,,Complete,Yes,Yes,2023-10-12,test_api_export_pdf.pdf,Yes,2021-06-06,Complete,,,,,,,,,,,,\n2,"Case Intake",,2,,,,,,,,,,,Yes,2021-06-05,"Sore Throat",Cough,"Shortness of Breath","Chest Pain",Headache,,Congestion,Fever,"Body Aches",,,,Complete,Yes,Yes,2021-06-07,test_api_export_pdf.pdf,No,,Complete,,,,,,,,,,,,\n2,Notifications,"Close Contacts",1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,"Janine Doe",2023-10-10,"(999) 999-9999",fake_email@gmail.com,Complete,,,,,,,\n2,Notifications,"Close Contacts",2,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,"Johnny Appleseed",2023-10-11,"(999) 999-9999",,Incomplete,,,,,,,\n'

## Reports

In [66]:
data = {
    'token': 'BFAB83D3B135FEF9891E504279ADA0E1',
    'content': 'report',
    'format': 'json',
    'report_id': '1996',
    'csvDelimiter': '',
    'rawOrLabel': 'raw',
    'rawOrLabelHeaders': 'raw',
    'exportCheckboxLabel': 'false',
    'returnFormat': 'json'
}
r = requests.post('https://dev-redcap.doh.wa.gov/api/',data=data)
print('HTTP Status: ' + str(r.status_code))
# print(r.json())
df_json = r.json()
df = pd.DataFrame.from_records(df_json)
df

HTTP Status: 200

,record_id,redcap_event_name,redcap_repeat_instrument,redcap_repeat_instance,first_name,last_name,phone_num,zip_code,dob,age,...,symptoms_yesno,symptom_onset,symptoms_exp,symptom_notes,test_yesno,test_positive_yesno,test_positive_date,test_upload,prior_covid_yesno,prior_covid_date
0,1,notifications_arm_1,,,,,,,,,...,,,,,,,,,,
1,1,personal_info_arm_1,,,John,Doe,(999) 999-9999,98105,2004-12-05,18,...,,,,,,,,,,
2,1,case_intake_arm_1,,1,,,,,,,...,1,2023-10-09,"1,2,7",,1,1,2023-10-10,test_api_export_image.png,0,
3,2,notifications_arm_1,,,,,,,,,...,,,,,,,,,,
4,2,personal_info_arm_1,,,Jane,Doe,(999) 999-9999,98105,1995-06-29,28,...,,,,,,,,,,
5,2,case_intake_arm_1,,2,,,,,,,...,1,2021-06-05,"1,2,3,4,5,7,8,9",,1,1,2021-06-07,test_api_export_pdf.pdf,0,
6,2,case_intake_arm_1,,1,,,,,,,...,1,2023-10-11,"1,2,8",,1,1,2023-10-12,test_api_export_pdf.pdf,1,2021-06-06
7,3,notifications_arm_1,,,,,,,,,...,,,,,,,,,,
8,3,personal_info_arm_1,,,Johnny,Appleseed,(999) 999-9999,98104,1989-10-13,34,...,,,,,,,,,,
9,3,case_intake_arm_1,,1,,,,,,,...,1,2023-10-08,1,,0,,,,0,
10,4,notifications_arm_1,,,,,,,,,...,,,,,,,,,,
11,4,personal_info_arm_1,,,Janine,Appleseed,(999) 999-9999,98107,1998-07-01,25,...,,,,,,,,,,
12,4,case_intake_arm_1,,1,,,,,,,...,1,2023-10-02,"6,7,8,9",,1,1,2023-10-03,,0,

## Files - optional attachments to individual records

In [67]:
data = {
    'token': 'BFAB83D3B135FEF9891E504279ADA0E1',
    'content': 'file',
    'action': 'export',
    'record': '1',
    'field': 'test_upload',
    'event': '',
    'returnFormat': 'json'
}
r = requests.post('https://dev-redcap.doh.wa.gov/api/',data=data)
print('HTTP Status: ' + str(r.status_code))

f = open('/tmp/file.raw.txt', 'wb')
f.write(r.content)
f.close()

HTTP Status: 400

FileNotFoundError: [Errno 2] No such file or directory: '/tmp/file.raw.txt'

# Survey Metadata

## Metadata (generic)

In [73]:
data = {
    'token': 'BFAB83D3B135FEF9891E504279ADA0E1',
    'content': 'metadata',
    'format': 'json',
    'returnFormat': 'json'
}
r = requests.post('https://dev-redcap.doh.wa.gov/api/',data=data)
print('HTTP Status: ' + str(r.status_code))
# print(r.json())
df_json = r.json()
df = pd.DataFrame.from_records(df_json)
df.head(10)

HTTP Status: 200

,field_name,form_name,section_header,field_type,field_label,select_choices_or_calculations,field_note,text_validation_type_or_show_slider_number,text_validation_min,text_validation_max,identifier,branching_logic,required_field,custom_alignment,question_number,matrix_group_name,matrix_ranking,field_annotation
0,record_id,demographics,,text,Study ID,,,,,,,,,,,,,
1,first_name,demographics,Personal Information,text,First Name,,,,,,,,,,,,,
2,last_name,demographics,,text,Last Name,,,,,,,,,,,,,
3,phone_num,demographics,,text,Phone Number,,,phone,,,,,,,,,,
4,zip_code,demographics,,text,ZIP Code,,,integer,10001,99999,y,,,,,,,
5,dob,demographics,,text,Date of birth,,,date_mdy,,,y,,,,,,,
6,age,demographics,,calc,Age (years),"rounddown(datediff([dob],'today','y'))",,,,,,,,,,,,
7,ethnicity,demographics,,radio,Ethnicity,"0, Hispanic or Latino|1, NOT Hispanic or Latin...",,,,,,,,LH,,,,
8,race,demographics,,dropdown,Race,"0, American Indian/Alaska Native|1, Asian|2, N...",,,,,,,,,,,,
9,gender,demographics,,radio,Gender,"0, Female|1, Male|2, Other|3, Prefer not to say",,,,,,,,,,,,

## Field Names

In [72]:
data = {
    'token': 'BFAB83D3B135FEF9891E504279ADA0E1',
    'content': 'exportFieldNames',
    'format': 'json',
    'returnFormat': 'json'
}
r = requests.post('https://dev-redcap.doh.wa.gov/api/',data=data)
print('HTTP Status: ' + str(r.status_code))
# print(r.json())
df_json = r.json()
df = pd.DataFrame.from_records(df_json)
df.head(15)

HTTP Status: 200

      original_field_name choice_value      export_field_name
0               record_id                           record_id
1              first_name                          first_name
2               last_name                           last_name
3               phone_num                           phone_num
4                zip_code                            zip_code
5                     dob                                 dob
6                     age                                 age
7               ethnicity                           ethnicity
8                    race                                race
9                  gender                              gender
10  demographics_complete               demographics_complete
11         symptoms_yesno                      symptoms_yesno
12          symptom_onset                       symptom_onset
13           symptoms_exp            1       symptoms_exp___1
14           symptoms_exp            2       symptoms_exp___2

## Forms/Instruments

In [74]:
data = {
    'token': 'BFAB83D3B135FEF9891E504279ADA0E1',
    'content': 'instrument',
    'format': 'json',
    'returnFormat': 'json'
}
r = requests.post('https://dev-redcap.doh.wa.gov/api/',data=data)
print('HTTP Status: ' + str(r.status_code))
# print(r.json())
df_json = r.json()
df = pd.DataFrame.from_records(df_json)
df

HTTP Status: 200

    instrument_name  instrument_label
0      demographics      Demographics
1          symptoms          Symptoms
2  test_information  Test Information
3    close_contacts    Close Contacts
4  work_information  Work Information

## Instrument Event Map

In [75]:
data = {
    'token': 'BFAB83D3B135FEF9891E504279ADA0E1',
    'content': 'formEventMapping',
    'format': 'json',
    'returnFormat': 'json'
}
r = requests.post('https://dev-redcap.doh.wa.gov/api/',data=data)
print('HTTP Status: ' + str(r.status_code))
# print(r.json())
df_json = r.json()
df = pd.DataFrame.from_records(df_json)
df

HTTP Status: 200

   arm_num    unique_event_name              form
0        1  personal_info_arm_1      demographics
1        1    case_intake_arm_1          symptoms
2        1    case_intake_arm_1  test_information
3        1  notifications_arm_1    close_contacts
4        1  notifications_arm_1  work_information

# Survery Settings and Other Information

## Users

In [76]:
data = {
    'token': 'BFAB83D3B135FEF9891E504279ADA0E1',
    'content': 'user',
    'format': 'json',
    'returnFormat': 'json'
}
r = requests.post('https://dev-redcap.doh.wa.gov/api/',data=data)
print('HTTP Status: ' + str(r.status_code))
# print(r.json())
df_json = r.json()
df = pd.DataFrame.from_records(df_json)
df

HTTP Status: 200

,username,email,firstname,lastname,expiration,data_access_group,data_access_group_id,design,alerts,user_rights,...,mobile_app,mobile_app_download_data,record_create,record_rename,record_delete,lock_records_all_forms,lock_records,lock_records_customization,forms,forms_export
0,caitlin.drover@doh.wa.gov,Caitlin.Drover@doh.wa.gov,Caitlin,Drover,,admin,1732,1,1,1,...,1,0,1,1,1,0,0,1,"{'demographics': 1, 'symptoms': 1, 'test_infor...","{'demographics': 1, 'symptoms': 1, 'test_infor..."
1,emily.pearman@doh.wa.gov,emily.pearman@doh.wa.gov,Emily,Pearman,,admin,1732,1,1,1,...,1,0,1,1,1,0,0,1,"{'demographics': 1, 'symptoms': 1, 'test_infor...","{'demographics': 1, 'symptoms': 1, 'test_infor..."

## User Roles

In [77]:
data = {
    'token': 'BFAB83D3B135FEF9891E504279ADA0E1',
    'content': 'userRole',
    'format': 'json',
    'returnFormat': 'json'
}
r = requests.post('https://dev-redcap.doh.wa.gov/api/',data=data)
print('HTTP Status: ' + str(r.status_code))
# print(r.json())
df_json = r.json()
df = pd.DataFrame.from_records(df_json)
df

HTTP Status: 200

,unique_role_name,role_label,design,alerts,user_rights,data_access_groups,reports,stats_and_charts,manage_survey_participants,calendar,...,mobile_app,mobile_app_download_data,record_create,record_rename,record_delete,lock_records_customization,lock_records,lock_records_all_forms,forms,forms_export
0,U-616XAYKNRT,Site Staff,0,1,0,0,1,1,1,1,...,0,0,1,0,0,0,0,0,"{'demographics': 3, 'symptoms': 3, 'test_infor...","{'demographics': 1, 'symptoms': 1, 'test_infor..."
1,U-6493J3CRKW,limited,0,0,0,0,1,1,1,1,...,0,0,1,0,0,0,0,0,"{'demographics': 2, 'symptoms': 2, 'test_infor...","{'demographics': 2, 'symptoms': 2, 'test_infor..."
2,U-697WTDJDRN,Project Manager,1,1,1,1,1,1,1,1,...,1,0,1,1,1,1,0,0,"{'demographics': 1, 'symptoms': 1, 'test_infor...","{'demographics': 1, 'symptoms': 1, 'test_infor..."

## Data Access Groups (DAGs)

In [78]:
data = {
    'token': 'BFAB83D3B135FEF9891E504279ADA0E1',
    'content': 'dag',
    'format': 'json',
    'returnFormat': 'json'
}
r = requests.post('https://dev-redcap.doh.wa.gov/api/',data=data)
print('HTTP Status: ' + str(r.status_code))
# print(r.json())
df_json = r.json()
df = pd.DataFrame.from_records(df_json)
df

HTTP Status: 200

  data_access_group_name unique_group_name  data_access_group_id
0                  Admin             admin                  1732
1                Limited           limited                  1747

## Logging

In [80]:
data = {
    'token': 'BFAB83D3B135FEF9891E504279ADA0E1',
    'content': 'log',
    'logtype': '',
    'user': '',
    'record': '',
    'beginTime': '2023-10-18 14:22',
    'endTime': '',
    'format': 'json',
    'returnFormat': 'json'
}
r = requests.post('https://dev-redcap.doh.wa.gov/api/',data=data)
print('HTTP Status: ' + str(r.status_code))
# print(r.json())
df_json = r.json()
df = pd.DataFrame.from_records(df_json)
df

HTTP Status: 200

,timestamp,username,action,details,record
0,2023-10-27 16:24,caitlin.drover@doh.wa.gov,Manage/Design,Export Logging (API),
1,2023-10-27 16:24,caitlin.drover@doh.wa.gov,Manage/Design,Export DAGs (API),
2,2023-10-27 16:24,caitlin.drover@doh.wa.gov,Manage/Design,Export user roles (API),
3,2023-10-27 16:24,caitlin.drover@doh.wa.gov,Manage/Design,Export users (API),
4,2023-10-27 16:24,caitlin.drover@doh.wa.gov,Manage/Design,Export instrument-event mappings (API),
...,...,...,...,...,...
533,2023-10-18 14:22,caitlin.drover@doh.wa.gov,Update record 2,"[instance = 2], record_id = '2'",2
534,2023-10-18 14:22,caitlin.drover@doh.wa.gov,Update record 2,demographics_complete = '0',2
535,2023-10-18 14:22,caitlin.drover@doh.wa.gov,Update record 1,"[instance = 2], record_id = '1'",1
536,2023-10-18 14:22,caitlin.drover@doh.wa.gov,Update record 1,demographics_complete = '0',1
537,2023-10-18 14:22,caitlin.drover@doh.wa.gov,Manage/Design,Create project using REDCap XML file,